language: node_js
node_js:
   - "9"
deploy:
  provider: script
  on:
    branch: master
    repo: Klezca/js-dev-en
    skip_cleanup: true
after_success:
- curl --data build=true -X POST $DOCKER_HUB_TRIGGER
